user_age= input("how old are you")
user_name= input ("what is your name")
user_surname= input("what is your surname")
user_liverplace= input("where do you live")
print("hi! nice to meet you"+ user_name + user_surname + "i like your surname you live in" + user_liverplace + "and you are"+ user_age + "years old") 